import image1 from "../../public/assets/hemkunt.jpg";

export const filterData = [
  {
    id: 1,
    key: "filter by",
  },
  {
    id: 2,
    key: "Apollo",
  },
  {
    id: 3,
    key: "Bedrock",
  },
  {
    id: 4,
    key: "Birla",
  },
  {
    id: 5,
    key: "Bridgestone",
  },
  {
    id: 6,
    key: "Ceat",
  },
  {
    id: 7,
    key: "Continental",
  },
  {
    id: 8,
    key: "Dunlop",
  },
  {
    id: 9,
    key: "Falkan",
  },
  {
    id: 10,
    key: "Firestone",
  },
  {
    id: 11,
    key: "Goodyear",
  },
  {
    id: 12,
    key: "Hankook",
  },
  {
    id: 13,
    key: "Jinyu",
  },
  {
    id: 14,
    key: "Jk Tyre",
  },
  {
    id: 15,
    key: "Kelly",
  },
  {
    id: 16,
    key: "Kenda",
  },
  {
    id: 17,
    key: "Kumho",
  },
  {
    id: 18,
    key: "Landsail",
  },
  {
    id: 19,
    key: "Linglong",
  },
  {
    id: 20,
    key: "Maruti",
  },
  {
    id: 21,
    key: "Mrf",
  },
];

export const productData = [
  {
    id: 1,
    brand: "Apollo",
    vehicle: "bike",
    model: "Alpha s1",
    varient: "140/60/R17",
    rating: 4.1,
    review: 12,
    price: 3727,
    warranty: 5,
    image: image1,
  },
  {
    id: 3,
    brand: "Apollo",
    vehicle: "bike",
    model: "ACTIZIP F5",
    varient: "100/80/17",
    rating: 3.2,
    review: 16,
    price: 1852,
    warranty: 5,
    image: image1,
  },
  {
    id: 4,
    brand: "Apollo",
    vehicle: "car",
    model: "TRAMPLR ST",
    varient: "140/60/R17",
    rating: 4.1,
    review: 12,
    price: 1873,
    warranty: 5,
    image: image1,
  },
  {
    id: 5,
    brand: "Apollo",
    vehicle: "scooter",
    model: "TRAMPLR XR",
    varient: "140/60/R17",
    rating: 4.1,
    review: 12,
    price: 2021,
    warranty: 5,
    image: image1,
  },
  {
    id: 6,
    brand: "Ceat",
    model: "Zoom",
    vehicle: "bike",
    varient: "140/60/R17",
    rating: 4.1,
    review: 106,
    price: 3302,
    warranty: 5,
    image: image1,
  },
  {
    id: 7,
    brand: "Ceat",
    vehicle: "bike",
    model: "Zoom Plus",
    varient: "140/60/R17",
    rating: 4.3,
    review: 166,
    price: 1844,
    warranty: 5,
    image: image1,
  },
  {
    id: 8,
    brand: "Ceat",
    vehicle: "car",
    model: "Zoom Rad",
    varient: "140/60/R17",
    rating: 3.2,
    review: 6,
    price: 3190,
    warranty: 5,
    image: image1,
  },
  {
    id: 9,
    brand: "Ceat",
    vehicle: "scooter",
    model: "Zoom Plus F",
    varient: "140/80-17",
    rating: 3.4,
    review: 5,
    price: 1738,
    warranty: 5,
    image: image1,
  },
  {
    id: 10,
    brand: "Mrf",
    vehicle: "bike",
    model: "Nylogrip zapper FS",
    varient: "100/80/17",
    rating: 3.6,
    review: 550,
    price: 3572,
    warranty: 2,
    image: image1,
  },
  {
    id: 11,
    brand: "Mrf",
    vehicle: "bike",
    model: "Nylogrip zapper-Fx",
    varient: "100/80/17",
    rating: 3.8,
    review: 205,
    price: 3671,
    warranty: 3,
    image: image1,
  },
  {
    id: 12,
    brand: "Mrf",
    vehicle: "car",
    model: "zapper s",
    varient: "100/80/17",
    rating: 3.7,
    review: 7,
    price: 1111,
    warranty: 3,
    image: image1,
  },
  {
    id: 13,
    brand: "Mrf",
    vehicle: "car",
    model: "Revz",
    varient: "100/80/R-17",
    rating: 3.9,
    review: 25,
    price: 3190,
    warranty: 2,
    image: image1,
  },
  {
    id: 14,
    brand: "Mrf",
    vehicle: "scooter",
    model: "Revz y",
    varient: "100/80/17",
    rating: 2.3,
    review: 5,
    price: 4780,
    warranty: 4,
    image: image1,
  },
  {
    id: 15,
    brand: "Maruti",
    vehicle: "scooter",
    model: "Maxima",
    varient: "100/80/17",
    rating: 4.3,
    review: 245,
    price: 1363,
    warranty: 6,
    image: image1,
  },
  {
    id: 16,
    brand: "JK Tyre",
    vehicle: "bike",
    model: "Blaze BF32",
    varient: "100/80/17",
    rating: 4.3,
    review: 50,
    price: 2760,
    warranty: 2,
    image: image1,
  },
  {
    id: 2,
    brand: "JK tyre",
    vehicle: "bike",
    model: "Blaze BR43",
    varient: "100/80/17",
    rating: 4.3,
    review: 24,
    price: 1706,
    warranty: 2,
    image: image1,
  },
];

export const priceData = [
  {
    id: 1,
    key: "Most Popular",
    type: "none",
  },
  {
    id: 2,
    key: "Price High to Low",
    type: "dec",
  },
  {
    id: 3,
    key: "Price Low to High",
    type: "inc",
  },
];

export const vehicleData = [
  {
    id: 1,
    key: "Bike",
  },
  {
    id: 2,
    key: "Car",
  },
  {
    id: 3,
    key: "Scooter",
  },
];
